new execsnoop, register based

diff --git a/execsnoop b/execsnoop
--- a/execsnoop
+++ b/execsnoop
@@ -1,4 +1,4 @@
-#!/usr/bin/perl
+#!/bin/bash
 #
 # execsnoop - trace process exec() with arguments.
 #             Written using Linux ftrace.
@@ -6,23 +6,27 @@
 # This shows the execution of new processes, especially short-lived ones that
 # can be missed by sampling tools such as top(1).
 #
-# USAGE: ./execsnoop [-h] [-n name]
+# USAGE: ./execsnoop [-hrt] [-n name]
 #
-# REQUIREMENTS: FTRACE CONFIG, sched:sched_process_exec tracepoint (you may
-# already have these on recent kernels), and Perl.
+# REQUIREMENTS: FTRACE and KPROBE CONFIG, sched:sched_process_fork tracepoint,
+# and either the stub_execve() or do_execve() kernel function. You may already
+# have these on recent kernels. And awk.
 #
 # This traces exec() from the fork()->exec() sequence, which means it won't
-# catch new processes that only fork(), and, it will catch processes that
-# re-exec. This instruments sched:sched_process_exec without buffering, and then
-# in user-space (this program) reads PPID and process arguments asynchronously
-# from /proc.
+# catch new processes that only fork(). With the -r option, it will also catch
+# processes that re-exec. It makes a best-effort attempt to retrieve the program
+# arguments and PPID; if these are unavailable, 0 and "[?]" are printed
+# respectively. There is also a limit to the number of arguments printed (by
+# default, 8), which can be increased using -a.
 #
-# If the process traced is very short-lived, this program may miss reading
-# arguments and PPID details. In that case, "<?>" and "?" will be printed
-# respectively. This program is best-effort, and should be improved in the
-# future when other kernel capabilities are made available. If you need a
-# more reliable tool now, then consider other tracing alternatives (eg,
-# SystemTap). This tool is really a proof of concept to see what ftrace can
+# This implementation is designed to work on older kernel versions, and without
+# kernel debuginfo. It works by dynamic tracing an execve kernel function to
+# read the arguments from the %si register. The stub_execve() function is tried
+# first, and then the do_execve() function. The sched:sched_process_fork
+# tracepoint, is used for the PPID. This program is a workaround that should be
+# improved in the future when other kernel capabilities are made available. If
+# you need a more reliable tool now, then consider other tracing alternatives
+# (eg, SystemTap). This tool is really a proof of concept to see what ftrace can
 # currently do.
 #
 # From perf-tools: https://github.com/brendangregg/perf-tools
@@ -49,102 +53,231 @@
 #
 # 07-Jul-2014	Brendan Gregg	Created this.
 
-use strict;
-use warnings;
-use POSIX qw(strftime);
-use Getopt::Long;
-my $tracing = "/sys/kernel/debug/tracing";
-my $flock = "/var/tmp/.ftrace-lock";
-my $tpdir = "sched/sched_process_exec";
-my $tptext = $tpdir; $tptext =~ s/\//:/;
-local $SIG{INT} = \&cleanup;
-local $SIG{QUIT} = \&cleanup;
-local $SIG{TERM} = \&cleanup;
-local $SIG{PIPE} = \&cleanup;
-local $SIG{HUP} = \&cleanup;
-$| = 1;
+### default variables
+tracing=/sys/kernel/debug/tracing
+flock=/var/tmp/.ftrace-lock; wroteflock=0
+opt_duration=0; duration=; opt_name=0; name=; opt_time=0; opt_reexec=0
+opt_argc=0; argc=8; max_argc=16; ftext=
+trap ':' INT QUIT TERM PIPE HUP	# sends execution to end tracing section
 
-### options
-my ($name, $help);
-GetOptions("name=s" => \$name,
-           "help"   => \$help)
-or usage();
-usage() if $help;
-sub usage {
-	print STDERR "USAGE: execsnoop [-h] [-n name]\n";
-	print STDERR "   eg,\n";
-	print STDERR "       execsnoop -n ls	# show \"ls\" cmds only.\n";
-	exit;
+function usage {
+	cat <<-END >&2
+	USAGE: execsnoop [-hrt] [-a argc] [-d secs] [name]
+	                 -d seconds      # trace duration, and use buffers
+	                 -a argc         # max args to show (default 8)
+	                 -r              # include re-execs
+	                 -t              # include time (seconds)
+	                 -h              # this usage message
+	                 name            # process name to match (REs allowed)
+	  eg,
+	       execsnoop                 # watch exec()s live (unbuffered)
+	       execsnoop -d 1            # trace 1 sec (buffered)
+	       execsnoop grep            # trace process names containing grep
+	       execsnoop 'log$'          # filenames ending in "log"
+END
+	exit
 }
 
-sub ldie {
-	unlink $flock;
-	die @_;
+function warn {
+	if ! eval "$@"; then
+		echo >&2 "WARNING: command failed \"$@\""
+	fi
 }
 
-sub writeto {
-	my ($string, $file) = @_;
-	open FILE, ">$file" or return 0;
-	print FILE $string or return 0;
-	close FILE or return 0;
+function end {
+	# disable tracing
+	echo 2>/dev/null
+	echo "Ending tracing..." 2>/dev/null
+	cd $tracing
+	warn "echo 0 > events/kprobes/$kname/enable"
+	warn "echo 0 > events/sched/sched_process_fork/enable"
+	warn "echo -:$kname >> kprobe_events"
+	warn "echo > trace"
+	(( wroteflock )) && warn "rm $flock"
 }
+
+function die {
+	echo >&2 "$@"
+	exit 1
+}
+
+function edie {
+	# die with a quiet end()
+	echo >&2 "$@"
+	exec >/dev/null 2>&1
+	end
+	exit 1
+}
+
+### process options
+while getopts a:d:hrt opt
+do
+	case $opt in
+	a)	opt_argc=1; argc=$OPTARG ;;
+	d)	opt_duration=1; duration=$OPTARG ;;
+	r)	opt_reexec=1 ;;
+	t)	opt_time=1 ;;
+	h|?)	usage ;;
+	esac
+done
+shift $(( $OPTIND - 1 ))
+if (( $# )); then
+	opt_name=1
+	name=$1
+	shift
+fi
+(( $# )) && usage
+
+### option logic
+(( opt_pid && opt_name )) && die "ERROR: use either -p or -n."
+(( opt_pid )) && ftext=" issued by PID $pid"
+(( opt_name )) && ftext=" issued by process name \"$name\""
+(( opt_file )) && ftext="$ftext for filenames containing \"$file\""
+(( opt_argc && argc > max_argc )) && die "ERROR: max -a argc is $max_argc."
+if (( opt_duration )); then
+	echo "Tracing exec()s$ftext for $duration seconds (buffered)..."
+else
+	echo "Tracing exec()s$ftext. Ctrl-C to end."
+fi
+
+### select awk
+if (( opt_duration )); then
+	[[ -x /usr/bin/mawk ]] && awk=mawk || awk=awk
+else
+	# workarounds for mawk/gawk fflush behavior
+	if [[ -x /usr/bin/gawk ]]; then
+		awk=gawk
+	elif [[ -x /usr/bin/mawk ]]; then
+		awk="mawk -W interactive"
+	else
+		awk=awk
+	fi
+fi
 
 ### check permissions
-chdir "$tracing" or ldie "ERROR: accessing tracing. Root? Kernel has FTRACE?" .
-    "\ndebugfs mounted? (mount -t debugfs debugfs /sys/kernel/debug)";
+cd $tracing || die "ERROR: accessing tracing. Root user? Kernel has FTRACE?
+    debugfs mounted? (mount -t debugfs debugfs /sys/kernel/debug)"
 
 ### ftrace lock
-if (-e $flock) {
-	open FLOCK, $flock; my $fpid = <FLOCK>; chomp $fpid; close FLOCK;
-	die "ERROR: ftrace may be in use by PID $fpid ($flock)";
+[[ -e $flock ]] && die "ERROR: ftrace may be in use by PID $(cat $flock) $flock"
+echo $$ > $flock || die "ERROR: unable to write $flock."
+wroteflock=1
+
+### build probe
+if [[ -x /usr/bin/getconf ]]; then
+	bits=$(getconf LONG_BIT)
+else
+	bits=64
+	[[ $(uname -m) == i* ]] && bits=32
+fi
+(( offset = bits / 8 ))
+function makeprobe {
+	func=$1
+	kname=execsnoop_$func
+	kprobe="p:$kname $func"
+	i=0
+	while (( i < argc + 1 )); do
+		# p:kname do_execve +0(+0(%si)):string +0(+8(%si)):string ...
+		kprobe="$kprobe +0(+$(( i * offset ))(%si)):string"
+		(( i++ ))
+	done
 }
-writeto "$$", $flock or die "ERROR: unable to write $flock.";
+# try stub_execve() first, then do_execve()
+makeprobe stub_execve
 
 ### setup and begin tracing
-writeto "nop", "current_tracer" or ldie "ERROR: disabling current_tracer.";
-writeto "1", "events/$tpdir/enable" or ldie "ERROR: enabling tracepoint " .
-    "\"$tptext\" (tracepoint missing in this kernel version?)";
-open TPIPE, "trace_pipe"  or warn "ERROR: opening trace_pipe.";
-printf "%-8s %6s %6s %s\n",  "TIME", "PID", "PPID", "ARGS";
+echo nop > current_tracer
+if ! echo $kprobe >> kprobe_events 2>/dev/null; then
+	makeprobe do_execve
+	if ! echo $kprobe >> kprobe_events; then
+		edie "ERROR: adding a kprobe for execve. Exiting."
+	fi
+fi
+if ! echo 1 > events/kprobes/$kname/enable; then
+	edie "ERROR: enabling kprobe for execve. Exiting."
+fi
+if ! echo 1 > events/sched/sched_process_fork/enable; then
+	edie "ERROR: enabling sched:sched_process_fork tracepoint. Exiting."
+fi
+(( opt_time )) && printf "%-16s " "TIMEs"
+printf "%6s %6s %s\n" "PID" "PPID" "ARGS"
 
-while (<TPIPE>) {
-	my ($taskpid, $rest) = split;
-	my ($task, $pid) = $taskpid =~ /(.*)-(\d+)/;
+#
+# Determine output format. It may be one of the following (newest first):
+#           TASK-PID   CPU#  ||||    TIMESTAMP  FUNCTION
+#           TASK-PID    CPU#    TIMESTAMP  FUNCTION
+# To differentiate between them, the number of header fields is counted,
+# and an offset set, to skip the extra column when needed.
+#
+offset=$($awk 'BEGIN { o = 0; }
+	$1 == "#" && $2 ~ /TASK/ && NF == 6 { o = 1; }
+	$2 ~ /TASK/ { print o; exit }' trace)
 
-	next if (defined $name and $name ne $task);
-
-	my $args = "$task <?>";
-	if (open CMDLINE, "/proc/$pid/cmdline") {
-		my $arglist = <CMDLINE>;
-		if (defined $arglist) {
-			$arglist =~ s/\000/ /g;
-			$args = $arglist;
-		}
-		close CMDLINE;
+### print trace buffer
+warn "echo > trace"
+( if (( opt_duration )); then
+	# wait then dump buffer
+	sleep $duration
+	cat -v trace
+else
+	# print buffer live
+	cat -v trace_pipe
+fi ) | $awk -v o=$offset -v opt_name=$opt_name -v name=$name \
+    -v opt_duration=$opt_duration -v opt_time=$opt_time -v kname=$kname \
+    -v opt_reexec=$opt_reexec '
+	# common fields
+	$1 != "#" {
+		# task name can contain dashes
+		comm = pid = $1
+		sub(/-[0-9][0-9]*/, "", comm)
+		sub(/.*-/, "", pid)
 	}
 
-	my $ppid = "?";
-	if (open STAT, "/proc/$pid/stat") {
-		my $fields = <STAT>;
-		if (defined $fields) {
-			$ppid = (split ' ', $fields)[3];
-		}
-		close STAT;
+	$1 != "#" && $(4+o) ~ /sched_process_fork/ {
+		cpid=$0
+		sub(/.* child_pid=/, "", cpid)
+		sub(/ .*/, "", cpid)
+		getppid[cpid] = pid
 	}
 
-	my $now = strftime "%H:%M:%S", localtime;
-	printf "%-8s %6s %6s %s\n", $now, $pid, $ppid, $args;
-}
+	$1 != "#" && $(4+o) ~ kname {
+		if (seen[pid])
+			next
+		if (opt_name && comm !~ name)
+			next
+
+		#
+		# examples:
+		# ... arg1="/bin/echo" arg2="1" arg3="2" arg4="3" ...
+		# ... arg1="sleep" arg2="2" arg3=(fault) arg4="" ...
+		# ... arg1="" arg2=(fault) arg3="" arg4="" ...
+		# the last example is uncommon, and may be a race.
+		#
+		if ($0 ~ /arg1=""/) {
+			args = comm " [?]"
+		} else {
+			args=$0
+			sub(/ arg[0-9]*=\(fault\).*/, "", args)
+			sub(/.*arg1="/, "", args)
+			gsub(/" arg[0-9]*="/, " ", args)
+			sub(/"$/, "", args)
+			if ($0 !~ /\(fault\)/)
+				args = args " [...]"
+		}
+
+		if (opt_time) {
+			time = $(3+o); sub(":", "", time)
+			printf "%-16s ", time
+		}
+		printf "%6s %6d %s\n", pid, getppid[pid], args
+		if (!opt_duration)
+			fflush()
+		if (!opt_reexec)
+			seen[pid] = 1
+	}
+
+	$0 ~ /LOST.*EVENT[S]/ { print "WARNING: " $0 > "/dev/stderr" }
+'
 
 ### end tracing
-cleanup();
-
-sub cleanup {
-	print "\nEnding tracing...\n";
-	close TPIPE;
-	writeto "0", "events/$tpdir/enable" or
-	    ldie "ERROR: disabling \"$tptext\"";
-	writeto "", "trace";
-	unlink $flock;
-	exit;
-}
+end
