more stderr

diff --git a/kernel/funccount b/kernel/funccount
--- a/kernel/funccount
+++ b/kernel/funccount
@@ -96,17 +96,17 @@ fi
 
 # setup and begin tracing
 if [[ ! -x $tracing ]]; then
-	echo "ERROR: accessing tracing. Root user? Kernel has FTRACE? Exiting."
+	echo >&2 "ERROR: accessing tracing. Root user? Kernel has FTRACE?"
 	exit 1
 fi
 sysctl -q kernel.ftrace_enabled=1	# doesn't set exit status
 if ! echo "$funcs" > $tracing/set_ftrace_filter; then
-	echo "ERROR: enabling \"$funcs\". Exiting."
+	echo >&2 "ERROR: enabling \"$funcs\". Exiting."
 	exit 1
 fi
 warn "echo nop > $tracing/current_tracer"
 if ! echo 1 > $tracing/function_profile_enabled; then
-	echo "ERROR: enabling function profiling. Exiting."
+	echo >&2 "ERROR: enabling function profiling. Exiting."
 	exit 1
 fi
 
diff --git a/kernel/functrace b/kernel/functrace
--- a/kernel/functrace
+++ b/kernel/functrace
@@ -98,16 +98,16 @@ fi
 
 # setup and commence tracing
 if [[ ! -x $tracing ]]; then
-	echo "ERROR: accessing tracing. Root user? Kernel has FTRACE? Exiting."
+	echo >&2 "ERROR: accessing tracing. Root user? Kernel has FTRACE?"
 	exit 1
 fi
 sysctl -q kernel.ftrace_enabled=1	# doesn't set exit status
 if ! echo "$funcs" > $tracing/set_ftrace_filter; then
-	echo "ERROR: enabling \"$funcs\". Exiting."
+	echo >&2 "ERROR: enabling \"$funcs\". Exiting."
 	exit 1
 fi
 if ! echo function > $tracing/current_tracer; then
-	echo "ERROR: setting current_tracer to \"function\". Exiting."
+	echo >&2 "ERROR: setting current_tracer to \"function\". Exiting."
 	exit 1
 fi
 
