improve locking

diff --git a/kernel/funccount b/kernel/funccount
--- a/kernel/funccount
+++ b/kernel/funccount
@@ -41,7 +41,7 @@
 tracing=/sys/kernel/debug/tracing
 opt_duration=0; duration=; opt_interval=0; interval=999999; opt_timestamp=0
 opt_tail=0; tcmd=cat; ttext=
-trap 'end=1' INT QUIT TERM PIPE	# sends execution to end tracing section
+trap 'quit=1' INT QUIT TERM PIPE	# sends execution to end tracing section
 
 function usage {
 	cat <<-END >&2
@@ -65,6 +65,11 @@ function warn {
 	if ! eval "$@"; then
 		echo >&2 "WARNING: command failed \"$@\""
 	fi
+}
+
+function die {
+	echo >&2 "$@"
+	exit 1
 }
 
 ### process options
@@ -94,25 +99,22 @@ else
 fi
 (( opt_duration && !opt_interval )) && interval=$duration
 
-### setup and begin tracing
-if ! cd $tracing; then
-	echo >&2 "ERROR: accessing tracing. Root user? Kernel has FTRACE?"
-	exit 1
-fi
+### check permissions
+cd $tracing || die "ERROR: accessing tracing. Root user? Kernel has FTRACE?
+    debugfs mounted? (mount -t debugfs debugfs /sys/kernel/debug)"
+
+### enable tracing
 sysctl -q kernel.ftrace_enabled=1	# doesn't set exit status
-if ! echo "$funcs" > set_ftrace_filter; then
-	echo >&2 "ERROR: enabling \"$funcs\". Exiting."
-	exit 1
-fi
+echo "$funcs" > set_ftrace_filter || die "ERROR: enabling \"$funcs\". Exiting."
 warn "echo nop > current_tracer"
 if ! echo 1 > function_profile_enabled; then
-	echo >&2 "ERROR: enabling function profiling. Exiting."
-	exit 1
+	echo > set_ftrace_filter
+	die "ERROR: enabling function profiling. Exiting."
 fi
 
 ### summarize
-end=0; secs=0
-while (( !end && (!opt_duration || secs < duration) )); do
+quit=0; secs=0
+while (( !quit && (!opt_duration || secs < duration) )); do
 	(( secs += interval ))
 	echo 0 > function_profile_enabled
 	echo 1 > function_profile_enabled
diff --git a/kernel/functrace b/kernel/functrace
--- a/kernel/functrace
+++ b/kernel/functrace
@@ -85,14 +85,29 @@ function warn {
 	fi
 }
 
+function end {
+	# disable tracing
+	echo 2>/dev/null
+	echo "Ending tracing..." 2>/dev/null
+	cd $tracing
+	warn "echo nop > current_tracer"
+	(( opt_pid )) && warn "echo > set_ftrace_pid"
+	warn "echo > set_ftrace_filter"
+	warn "echo > trace"
+	(( wroteflock )) && warn "rm $flock"
+}
+
 function die {
 	echo >&2 "$@"
 	exit 1
 }
 
-function ldie {
-	[[ -e $flock ]] && rm $flock
-	die "$@"
+function edie {
+	# die with a quiet end()
+	echo >&2 "$@"
+	exec >/dev/null 2>&1
+	end
+	exit 1
 }
 
 ### process options
@@ -117,31 +132,32 @@ else
 	echo "Tracing \"$funcs\"$pidtext... Ctrl-C to end."
 fi
 
+### check permissions
+cd $tracing || die "ERROR: accessing tracing. Root user? Kernel has FTRACE?
+    debugfs mounted? (mount -t debugfs debugfs /sys/kernel/debug)"
+
 ### ftrace lock
 [[ -e $flock ]] && die "ERROR: ftrace may be in use by PID $(cat $flock) $flock"
 echo $$ > $flock || die "ERROR: unable to write $flock."
+wroteflock=1
 
 ### setup and commence tracing
-if ! cd $tracing; then
-	ldie "ERROR: accessing tracing. Root user? Kernel has FTRACE?"
-fi
 sysctl -q kernel.ftrace_enabled=1	# doesn't set exit status
 read mode < current_tracer
-[[ "$mode" != "nop" ]] && ldie "ERROR: ftrace active (current_tracer=$mode)"
+[[ "$mode" != "nop" ]] && edie "ERROR: ftrace active (current_tracer=$mode)"
 if (( opt_pid )); then
 	if ! echo $pid > set_ftrace_pid; then
-		ldie "ERROR: setting -p $pid (PID exist?). Exiting."
+		edie "ERROR: setting -p $pid (PID exist?). Exiting."
 	fi
 fi
 if ! echo "$funcs" > set_ftrace_filter; then
-	ldie "ERROR: enabling \"$funcs\". Exiting."
+	edie "ERROR: enabling \"$funcs\". Exiting."
 fi
 if ! echo function > current_tracer; then
-	ldie "ERROR: setting current_tracer to \"function\". Exiting."
+	edie "ERROR: setting current_tracer to \"function\". Exiting."
 fi
 
 ### print trace buffer
-end=0; secs=0
 warn "echo > trace"
 if (( opt_duration )); then
 	sleep $duration
@@ -157,10 +173,4 @@ else
 fi
 
 ### end tracing
-echo 2>/dev/null
-echo "Ending tracing..." 2>/dev/null
-warn "echo nop > current_tracer"
-(( opt_pid )) && warn "echo > set_ftrace_pid"
-warn "echo > set_ftrace_filter"
-warn "echo > trace"
-warn "rm $flock"
+end
